Add explicit sub-canopy 3-layers effect in photolysis and gas-phase (…
noaa-oar-arl/AQM pull request #26
Opened 2024-11-25 23:30 UTC by iri01

…cb6r3_ae6_aq mechanism)

activated with CANOPY_SHADE namelist parameter.

## PR Checklist
- [x] This PR has been tested on an RDHPCS machine and/or WCOSS2. Please select below:
  - [x] RDHPCS.
  - [ ] WCOSS2.

- [x] This PR has been tested with the ufs-srweather-app workflow online-cmaq branch.

- [x] New or updated input data is required by this PR. 

- [x] Baselines are expected to change.

## Description

## Issue(s) addressed

## Dependencies

2024-11-26 17:17 UTC, drnimbusrain requested changes
Hi Irena,

Looks OK as I go through it this morning. I think after retroactively, at our next meeting we go through these changes.  I only have a small comment on the canopy mask and FCH threshold here compared to the recent results you have shown.  

I do have one major question here.   Are we missing your _hrdriver.F_ changes here where the gas phase solver is applied on canopy levels? If so please add the required changes (in make files, src/model/src/hrdriver.F files, etc.) here.

 Also, thinking ahead, we have moved to using the Rosenbrock (RB) solver instead of EBI in future AQMv8.  Therefore, I think if possible you should add the corresponding gas phase solver/driver changes for RB to this PR (e.g., https://github.com/USEPA/CMAQ/blob/5.2.1/CCTM/src/gas/ros3/rbdriver.F#L638), so that when we merge in CMAQ54 updates we get the canopy changes for AQMv8 RB solver option. 

Thank you!

2024-11-26 17:17 UTC, drnimbusrain commented on src/model/src/can_mask.F90
> +           .OR.                Met_Data%FCH (COL,ROW)  .LT. 0.5     &
I thought in your recent presentations we are using a FCH threshold of 3.0 meters?

2024-11-26 17:17 UTC, drnimbusrain commented on src/model/src/can_mask.F90
> +           .OR.                Met_Data%FCH (COL,ROW)  .LT. 0.5     &
I thought in your recent presentations we are using a FCH threshold of 3.0 meters?

2024-11-27 16:22 UTC, iri01 commented on src/model/src/can_mask.F90
> +           .OR.                Met_Data%FCH (COL,ROW)  .LT. 0.5     &
As discussed, the FCH threshold I used in my runs is 0.5 m.

2024-12-02 16:22 UTC, drnimbusrain reviewed
@iri01 Thanks looks good from my perspective here.  Just need a short test of this package (i.e., [feature/aqm_canopy_phot3lev](https://github.com/noaa-oar-arl/AQM/tree/feature/aqm_canopy_phot3lev)) with CMAQ521 still). using both the HR (EBI) and RB solvers with canopy on - off.  Then we can merge!  Can you test this package with both solvers to make sure they work and get results as expected?

2025-02-14 20:01 UTC, drnimbusrain requested changes
Looks OK to me, great work in getting this in!  I think maybe only a few comments at the top of the new canopy routines added, briefly explaining what they do starting a change log for tracking changes.

2025-02-14 20:01 UTC, drnimbusrain commented on src/model/src/GRID_CONF.F
> +C.......................................................................
@iri01  Please just a small comment with date  here about what you changed for our local AQM version of GRID_CONF with canopy.

2025-02-14 20:01 UTC, drnimbusrain commented on src/model/src/can_levs_defn.F90
> +
@iri01 Just for now and future updates, a brief date and description of what this new module does (and briefly what subroutines are included) for everyone's record.

2025-02-14 20:01 UTC, drnimbusrain commented on src/model/src/can_mask.F90
> +
@iri01 Just for now and future updates, a brief date and description of what this new module does (and briefly what subroutines are included) for everyone's record.

2025-02-14 20:01 UTC, drnimbusrain commented on src/model/src/can_trans_mod.F90
> +
@iri01 Just for now and future updates, a brief date and description of what this new module does (and briefly what subroutines are included) for everyone's record.

2025-02-14 20:01 UTC, drnimbusrain commented on src/model/src/hrdata_mod.F
> +C*************************************************************************
Small comment on your updates and date.

2025-03-03 21:27 UTC, iri01 commented on src/model/src/GRID_CONF.F
> +C.......................................................................
This a CCTM local version of GRID_CONF (copy from CCTM/grid/cartesian/GRID_CONF.F) with added sub-canopy layers parameters. Dated on January 20, 2025. See lines:

      INTEGER, PARAMETER :: NLAYC = 3 ! # of canopy layers for shading effects
      INTEGER, SAVE :: NLAYT
      INTEGER, SAVE :: MXCELLS_CAN
      INTEGER, SAVE :: MXBLKS_CAN
...
            NLAYT = NLAYS + NLAYC
            WRITE( LOGDEV, *) 'GRID_INIT: CANOPY LAYERS = ', NLAYC, NLAYT
            MXCELLS_CAN = NCOLS * NROWS * NLAYT
            MXBLKS_CAN  = 1 + ( MXCELLS_CAN - 1 ) / BLKSIZE
            WRITE( LOGDEV, *) 'GRID_INIT: MXBLKS_CAN = ', MXBLKS_CAN, MXCELLS_CAN,BLKSIZE

2025-03-03 21:29 UTC, drnimbusrain commented on src/model/src/GRID_CONF.F
> +C.......................................................................
Great, please add comments into the code

2025-03-03 21:37 UTC, iri01 commented on src/model/src/can_mask.F90
> +
A new canopy module that defines the canopy shaded columns based on 5 canopy datasets. 
Used in other canopy routines and the gas-phase driver routines (EBI/ROS3 hrdrriver/rbdriver)

2025-03-04 21:50 UTC, iri01 commented on src/model/src/hrdata_mod.F
> +C*************************************************************************
Date: 2024/06. Modified version of EBI gas-phase solver (CB6 mechanism) with added diagnostics for gas-phase tendencies and other auxiliary diagnostics.

2025-03-04 22:14 UTC, iri01 commented on src/model/src/can_levs_defn.F90
3 canopy sub-layers are initialized with the meteorology vars (temperature, humidity, pressure etc. ) being interpolated on to the canopy layers height from the 1hy model layer and 2m diagnostic values from the LSM.

2025-03-04 22:17 UTC, iri01 commented on src/model/src/can_mask.F90
Date: 2024/04. Description: A new canopy module defines a mask of the canopy shaded columns based on various criteria for 5 canopy datasets. Used in other canopy routines and the gas-phase driver routines (EBI/ROS3)

2025-03-05 00:43 UTC, drnimbusrain commented
@iri01 These comments are great, but can you please add them as commits directly in the top of these respective new canopy codes/routines in your branch?

2025-03-05 02:53 UTC, iri01 commented on src/model/src/can_trans_mod.F90
Date: 2024/09. Description: New canopy routine that transfers mass of chemical tracers between the canopy layers and the model layers, and conserves mass.

2025-03-05 02:54 UTC, iri01 commented on src/model/src/hrdata_mod.F
Date: 2024/06. Modified version of EBI gas-phase solver where the gas-phase chemistry (CB6 and ROS3 mechanisms) is computed over canopy-shaded regions, as defined in "canopy_mask" routine, on 3 sub-canopy layers. Diagnostics for gas-phase tendencies and other auxiliary diagnostics are also added.

2025-03-05 02:55 UTC, iri01 commented on src/model/src/hrdriver.F
Date: 2024/06. Modified version of EBI gas-phase solver where the gas-phase chemistry (CB6 and ROS3 mechanisms) is computed over canopy-shaded regions, as defined in "canopy_mask" routine, on 3 sub-canopy layers. Diagnostics for gas-phase tendencies and other auxiliary diagnostics are also added.

2025-03-05 03:00 UTC, iri01 commented on src/model/src/phot.F
Date: 2024/06. Description: Modified version of photolysis routine, where the photolysis rates over canopy-shaded regions are calculated on 3 sub-canopy layers. Activate photolysis diagnostics. The routine is used in the gas-phase chemistry solvers (EBI/ROS3) routines.

2025-03-07 13:41 UTC, drnimbusrain approved these changes

2025-03-07 13:41 UTC, merged